# Development Stage
# FROM node:18 AS development
# WORKDIR /app
# COPY package*.json ./
# RUN npm install
# COPY . .
# CMD ["npm", "start"]

# # Production Stage
# FROM node:18 AS production
# WORKDIR /app
# COPY package*.json ./
# RUN npm install --production
# COPY . .
# RUN npm run build
# FROM nginx:alpine
# COPY --from=production /app/build /usr/share/nginx/html
# EXPOSE 80
# CMD ["nginx", "-g", "daemon off;"]

# FROM node:18 AS development
# WORKDIR /app
# COPY package*.json ./
# RUN npm install
# COPY . .
# CMD ["npm", "start"]

FROM node:24

# WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .
EXPOSE 3000
CMD ["npm", "start"]