services:
  # =========================
  # FRONTEND
  # =========================
  frontend:
    build:
      context: ./frontend
      target: ${MODE}
    container_name: frontend

    ports:
      - "3000:3000"

    depends_on:
      - backend

    environment:
      - NODE_ENV=${MODE}

    # Development only
    volumes:
      - ./frontend:/app
      - /app/node_modules

    restart: unless-stopped

  # =========================
  # BACKEND
  # =========================
  backend:
    build:
      context: ./backend
      target: ${MODE}

    container_name: backend

    ports:
      - "8000:8000"

    env_file:
      - ./backend/.env

    environment:
      - NODE_ENV=${MODE}
      - MONGO_URI=mongodb://db:27017/webRTC_video_app
      - REDIS_URL=redis://redis:6379
      - REDIS_HOST=redis
      - REDIS_PORT=6379

    depends_on:
      - db
      - redis
      - email_ervice

    # Development only
    volumes:
      - ./backend:/app
      - /app/node_modules

    restart: unless-stopped

  # ================================
  # emsil service server
  # ============================
  email_ervice:
    build: ./emailService

    container_name: emailService

    ports:
      - "8010:8010"

    env_file:
      - ./emailService/.env

    environment:
      - NODE_ENV=${MODE}
      - REDIS_URL=redis://redis:6379

    volumes:
      - ./emailService:/app
      - /app/node_modules

    restart: unless-stopped

    depends_on:
      - db
      - redis

  # =========================
  # MONGODB
  # =========================
  db:
    image: mongo:latest

    container_name: mongodb

    ports:
      - "27017:27017"

    volumes:
      - mongodb_data:/data/db

    restart: unless-stopped

  # =========================
  # REDIS
  # =========================
  redis:
    image: redis:7.2-alpine

    container_name: redis

    ports:
      - "6379:6379"

    volumes:
      - redis_data:/data

    restart: unless-stopped

volumes:
  mongodb_data:
  redis_data:
